apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.backend.namespace }}
  name: {{ .Values.backendservice.name }}
spec:
  type: {{ .Values.backendservice.type }}
  selector:
    app: {{ .Values.backend.app }}
  ports:
    - port: {{ .Values.backendservice.port }}
      targetPort: {{ .Values.backendservice.targetPort }}

