apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.frontend.namespace }}
  name: {{ .Values.frontendservice.name }}
spec:
  type: {{ .Values.frontendservice.type }}
  selector:
    app: {{ .Values.frontend.app }}
  ports:
    - port: {{ .Values.frontendservice.port }}
      targetPort: {{ .Values.frontendservice.targetPort }}
      nodePort: {{ .Values.frontendservice.nodePort }}
