apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-data-pv-dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  capacity:
    storage: 2Gi
  hostPath:
    path: /home/mohamed-atef/data/
