apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-slave
  labels:
    app: jenkins-slave
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-slave
  template:
    metadata:
      labels:
        app: jenkins-slave
    spec:
      containers:
      - name: jenkins-slave
        image: kareemelkasaby/jenkins-slave-java-11:latest
        ports:
        - containerPort: 22
        volumeMounts:
          - mountPath: /var/run/docker.sock 
            name: jenkins-home
      volumes:
      - name: jenkins-home
        hostPath :
           path: /var/run/docker.sock 